### ISSUE TITLE
The right way t predict an image

### ISSUE THREAD

**Issue by EngMoAmri** [Optimization-AI/LibAUC#1]
I was wondering if this is the right way to predict an image from path

```
import torch
import torchvision.transforms as transforms
from PIL import Image
import numpy as np
from libauc.models import DenseNet121
model = DenseNet121(pretrained=False, last_activation='sigmoid', activations='relu', num_classes=1)
PATH = 'edema_optimized_model.pth'
model.load_state_dict(torch.load(PATH,map_location='cpu'))
# Create the preprocessing transformation here
transform = transforms.Compose([
transforms.Resize((224,224)),
transforms.ToTensor(),
transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))
])

# load your image(s)
image = Image.open("CheXpert-v1.0-small/valid/patient64552/study1/view1_frontal.jpg").convert('RGB')
# Transform
input = transform(image)
# # unsqueeze batch dimension, in case you are dealing with a single image
input = input.unsqueeze(0)
# Set model to eval
model.eval()
# Get prediction
output = model(input)
print(output)
```

**Comment by yzhuoning** [comment]
I use `cv2` to preprocess the input image, but `PIL` should give a similar performance.

**Comment by EngMoAmri** [comment]
I used a for loop to read images at valid.csv then predict these images then draw confusion matrix but I didn't get the results which I wanted
     0     1
0[[99, 90],
1 [2,   43 ]]
Is this result ok? By the way I get val auc 0.923

**Comment by yzhuoning** [comment]
It depends on your training settings, e.g., batch size, number of epochs, pretraining. If you follow the given example, you should get val auc around 0.940.

**Comment by EngMoAmri** [comment]
I couldn't use your training settings because the pc I used isn't good enough to handle your settings 😓.
I was wondering how the confusion matrix will be with val auc 0.940 😅
Thank you for your time
