### ISSUE TITLE
Negative Loss

### ISSUE THREAD

**Issue by k78ma** [Optimization-AI/LibAUC#10]
I have been using AUC Maximization for experiments relating to chest X-Ray datasets. For some experiments, I have been encountering negative loss values; I don't think this is supposed to be theoretically possible. My implementation simply uses AUCMLoss and PESG from LibAUC. Any clarification on this issue would be appreciated.

Thanks!

**Comment by yzhuoning** [comment]
The negative values could come from the inaccurate estimation for imbalance ratio (`imratio`) in your dataset. For example, you set `imratio=0.1` in `AUCMLoss()`, but the real number of `imratio` for each mini-batch is `imratio>>0.1` , this will make the loss become negative.

I plan to release a new version (to avoid this issue) later this week. If you find our library useful, please star our repo. Thanks!

**Comment by k78ma** [comment]
Thanks for your help!

**Comment by optmai** [comment]
Hello, 

Thank you for your interest in our library. The output loss is not meant to be monitoring the progress of optimizer. Unlike traditional deep learning tools that optimizes the decomposable empirical losses (e.g., CE loss), AUC maximization is optimizing a min-max objective. It is not guaranteed the mini-batch loss is always non-negative. We will develop a new tool to monitor the progress of optimizer.
