### ISSUE TITLE
pos_num in ImbalanceSampler

### ISSUE THREAD

**Issue by hyunjaecho94** [Optimization-AI/LibAUC#12]
What is ImbalanceSampler's parameter pos_num supposed to mean? If we have a binary classification, is it the positive label? For example, with cancer and no cancer task, 0 means no cancer, and 1 is cancer, then pos_num is 1? Thanks!

**Comment by yzhuoning** [comment]
`pos_num` refers to the number of samples from positive class in a mini-batch. For instance, you set `pos_num=10`, meaning that there will be 10 examples randomly sampled from positive class in each mini-batch.  In our default setting, we denote positive class (minority class) as 1 and negative class (majority class) as 0. 

I am working on a tutorial to demonstrate how to use `ImbalanceSampler`, and it will be released soon. If you find our library useful, please help star the repo! Thanks!
