### ISSUE TITLE
LibAUC code

### ISSUE THREAD

**Issue by aashiqmuhamed** [Optimization-AI/LibAUC#13]
I was wondering whether you could also commit the core library code to this repository? I just see examples and scripts, and no code for the actual library.

Are there plans to integrate the optimizers with other large scale training frameworks such as DeepSpeed? Have you tested the optimizers on large models? (say >500M parameters)

**Comment by jacobdang** [comment]
It appears that the actual library and code are not yet released.  Running the examples according to the provided instruction only gives an error message: `AttributeError: module 'libauc' has no attribute 'losses'`.  Wondering when will the library be released?

**Comment by yzhuoning** [comment]
@jacobdang The source file is actually available [here](https://github.com/Optimization-AI/LibAUC/releases/tag/v1.1.8). You can simply download it and use `pip` to install. After the installation, the source code is located on your local python directory. We are currently working on a major release and expect to push this update sometime next month.

Regarding your code, it is hard to diagnose why you ran into this error without further information provided (e.g., which version, tutorials, etc.).

**Comment by lengstrom** [comment]
I think what @jacobdang means here is that the source files for the actual library are not hosted on GitHub -- the GitHub repo and the releases page only contain code for the tutorials/examples not the python module.

**Comment by tstuessi** [comment]
Seconded, I would also prefer to have the source files for the library on Github - I've been using this library quite a bit and it would be useful to be able to search the source files in a browser.

**Comment by marcmk6** [comment]
It would be nice to have source code. I'm currently struggling running one of the examples as it's extremely slow for me to download a dataset. If the source code is available, there can be flexible solutions.
