### ISSUE TITLE
关于09示例的实验

### ISSUE THREAD

**Issue by yanruiD** [Optimization-AI/LibAUC#15]
对于09示例，论文里消融实验考虑了S1≠S2，代码里是如何体现的，感谢指出，谢谢大佬。

**Comment by yzhuoning** [comment]
`CompositionalLoss`是一个dynamic loss，比如iteration0和iteration1的backend分别调用了`CELoss`和`AUCMLoss`，间接的实现了S1≠S2，同时也避免了使用多个dataloader。
