### ISSUE TITLE
关于09示例的技巧

### ISSUE THREAD

**Issue by yanruiD** [Optimization-AI/LibAUC#16]
我注意到在09的示例中，在论文的消融实验中，k>1时，对AUC的得分影响挺大。在代码里是如何展现调节k的值的呢，不太确定，望指教。谢谢大佬。

**Comment by yzhuoning** [comment]
目前的版本只提供了k=1的示例，k>1的话会在将来的更新中放出来

**Comment by yzhuoning** [comment]
在09示例中，α的值和外部的lr一致，如果需要调节的话可以把lr0单独赋值并传到Optimizer里面即可。比如，可以让lr0比lr稍小一些。
