### ISSUE TITLE
Training the rest of labels of chexpert dataset 

### ISSUE THREAD

**Issue by MeedoAmeri** [Optimization-AI/LibAUC#2]
How can I train  the rest of labels,  what modifications should I do?

**Comment by yzhuoning** [comment]
You can just set `class_id`=0,1,2,3,4`.

**Comment by MeedoAmeri** [comment]
Sorry, I meant the rest labels other than these 5 labels like pneumonia and others

**Comment by yzhuoning** [comment]
Try this `train_cols=['pneumonia', 'Others labels']`
