### ISSUE TITLE
ImbalancedDataGenerator() ISSUE

### ISSUE THREAD

**Issue by rohan1561** [Optimization-AI/LibAUC#23]
Hello, nice work! I was just wondering why you convert every label <= split index into 0 and all others into 1 (lines 62 and 63 in utils/generator.py)? That makes the task binary but it just pools several classes into two. Have I misunderstood something? Why would one want to do this?

**Comment by yzhuoning** [comment]
Hello, this is one way that you could construct the imbalanced dataset with customized imbalanced ratio (e.g., pos/all). You can also try other methods to construct imbalanced dataset (e.g., predicting one class vs the rest classes) or directly use the naturally imbalanced datasets.
