### ISSUE TITLE
Where to find codes loss and optimizers, metrics?

### ISSUE THREAD

**Issue by seoulsky-field** [Optimization-AI/LibAUC#27]
Hello, I'm a student that studies medical AI.

First, I truly appreciate to share your library.
I want to use AUCM loss and PESG optimizers with variety optimizers and losses.
But there are some parameters to check before using the loss or optimizers. (like a, b parameters in PESG, issue on #24 )

So I want to see codes what parameters do actually!
However, I cannot find the codes about them. Where can I find?

Thank you so much.

**Comment by seoulsky-field** [comment]
@yzhuoning Thank you very much!

**Comment by rbeeli** [comment]
Hi @yzhuoning 
What's the reason why the source code is not in the repository on GitHub? That's unusual. Would be nice to have it in the GitHub repository as well.
Thank you.
