### ISSUE TITLE
The difference on AUC margin loss  V1 & V2

### ISSUE THREAD

**Issue by wxr99** [Optimization-AI/LibAUC#28]
Great job by the authors.  We are now optimizing the AUC margin loss on a new federated optimization scheme, but we found two versions of AUC margin loss methods in the /libauc/losses, respectively named AUCMLoss_V1 & AUCMLoss_V2 in auc.py and losses_v1.py. The main difference is about the positive ratio p (V1 includes but v2 didn't), and it directly influences the optimization. Then, why or which should I concentrate on?

**Comment by wxr99** [comment]
And both are used in the given examples, like federated examples and basic examples given by authors, so it really made me confused.

**Comment by yzhuoning** [comment]
Please use `V1` (by default) for now. We are still testing `V2` (to remove `p` in the loss). Thanks!

**Comment by wxr99** [comment]
It will be a great job if no prior ratio is introduced, we hope to see a more simple version of AUC loss
