### ISSUE TITLE
Using AUCM_MultiLabel for multi-class classification but found the loss returns 0

### ISSUE THREAD

**Issue by ynyang94** [Optimization-AI/LibAUC#31]
Hi, 
I'm using your library for our project. Our project basically need to classify the images into 6 classes. So I'm trying to use AUCM_MultiLabel for this task. The argument I input is the true label (value from 0 to 5), and the estimated index (discrete value from 0 to 5). But it always return 0.
When I trying to use the raw estimate inputting into this function, meaning the 6x1 tensor from the model with the true label. It always give me error on tensor dimension, which should be equal to 1.
Could you help figure where I'm wrong? or where I didn't understand? Thanks a lot!

**Comment by yzhuoning** [comment]
Hi Yufeng,

To use AUCM_MultiLabel, your prediction and label tensors need to be reshaped into (B, C), where B is the batch size and C is the number of classes in your dataset. If your labels tensor is in either (B,) or (B, 1) format, it will not be compatible with the current multi-label loss. In other words, you can convert your label tensors to one-hot format (B, C) and change the number of classes for your model output to C. This should work with the AUCM_MultiLabel loss.

**Comment by JerryZ01728** [comment]
Hello, I have changed labels tensor to (B, C), but when training, val_auc doesn't increase. This means that the loss doesn't work. If you can explain why this happened, I would be appreciate.
