### ISSUE TITLE
PESG中的参数vref

### ISSUE THREAD

**Issue by yanruiD** [Optimization-AI/LibAUC#34]
Large-scale Robust Deep AUC Maximization论文中采取了累计平均值vref，它发挥了什么样的作用，对参数更新影响大吗

**Comment by optmai** [comment]
Thank you for your interest in our library. 

Vref plays a role of improving generalization. The corresponding parameter is called epoch decay. You can tune this parameter.

**Comment by optmai** [comment]
Please let me know if you have any other questions.
