### ISSUE TITLE
Label in CheXpert dataset.

### ISSUE THREAD

**Issue by mxadorable** [Optimization-AI/LibAUC#47]
Hi, thank you for share your great work.
Could you please explain why the labels of 'Edema', 'Atelectasis' are replaced in this way?
if col in ['Edema', 'Atelectasis']:
                self.df[col].replace(-1, 1, inplace=True)

As far as I know, in the chexpert labels, -1 represents negative, and 1 represent positive. I see that some diseases replace -1 with 0, but why the two diseases are different?

Thank you so much!

**Comment by optmai** [comment]
Thank you for your interest!  Please let us know if you have additional questions.
