### ISSUE TITLE
Integrating torchvision models and Lightning

### ISSUE THREAD

**Issue by vasudev13** [Optimization-AI/LibAUC#6]
Hi, awesome work on AUC maximization. I'm trying to reproduce the second step from https://arxiv.org/abs/2012.03173 , I sort of have a different pre-training approach. 

However, I'm using a `torchvision.models.resnet` instead of models from `libauc`, it appears it should fairly easy to use the former when replicated the mentioned tutorial for CheXpert. (Essentially is `libauc.models.ResNet18` replaceable with `torchvision.models.resnet18` ?)

Also, I'm using libraries like `pytorch-lightning` and `wandb`, do you expect any possible irregularities I might face if I use them with `LibAUC`?

Thanks for your time and amazing work!

**Comment by yzhuoning** [comment]
Thanks! It should work fine with torchvision models, but just remember to check if you need to include an activation function after model outputs. I haven't checked compatibility with pytorch-lightning yet, but I plan to do it in near future.

**Comment by vasudev13** [comment]
Awesome, thanks so much. I'll circle back incase I need some more inputs on usage.

**Comment by RoyBenjamin** [comment]
@vasudev13  I am wondering if you managed to use `LibAUC` with `pytorch-lightning` as I am experiencing this issue:
`TypeError: step() got an unexpected keyword argument 'closure'`
When using PESG as the optimizer.
