### ISSUE TITLE
Issues with Example 02

### ISSUE THREAD

**Issue by dingyan20** [Optimization-AI/LibAUC#7]
In Example 02, the train_loss is the running loss for the last iteration of the for loop, not for the epoch. For the train_auc, each chunk of the train_pred (y_pred) was calculated with a different model (a updated model).

**Comment by yzhuoning** [comment]
Thanks for the feedback! For demo purpose, I simply use running `train_auc/train_loss` to estimate real `train_auc/train_loss`. If we want to do some comparisons on these measures, we should re-evaluate the model after training, which should give more accurate results. 

Close it for now. Please re-open if you have other questions.
